name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master # This workflow will run whenever you push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps:
      - name: Checkout repository # Step to check out your repository code
        uses: actions/checkout@v4 # Uses the official GitHub action for checking out code

      - name: Set up Node.js # Step to set up Node.js environment
        uses: actions/setup-node@v4 # Uses the official GitHub action for setting up Node.js
        with:
          node-version: '20' # Specify the Node.js version you want to use (e.g., 18, 20, 22)
          cache: 'npm' # Caches npm dependencies to speed up subsequent builds

      - name: Install dependencies # Step to install your project's npm dependencies
        run: npm install

      - name: Build Vite app # Step to build your Vite application
        run: npm run build # Assumes you have a "build" script in your package.json (e.g., "build": "vite build")

      - name: Deploy to GitHub Pages # Step to deploy the built code to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4 # A popular GitHub action for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GitHub token provided by GitHub Actions
          publish_dir: ./dist # Specifies the directory containing your built files (Vite's default output is 'dist')
          publish_branch: gh-pages # Specifies the branch to which the built files will be pushed
